/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'deika' at '3/21/16 9:02 PM' with Gradle 2.9
 *
 * @author deika, @date 3/21/16 9:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
